name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Build
      run: bun run build:github
      
    - name: Prepare docs folder
      run: |
        rm -rf docs
        mkdir docs
        cp -r dist/* docs/
      
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git diff --quiet && git diff --staged --quiet || git commit -m "Update GitHub Pages build"
        git push 